openapi: 3.0.3
info:
  title: STD23038
  version: 1.0.0
servers:
  - url: "https://localhost.std23038.com"
paths:
  /competition:
    get:
      tags:
        - Competitions
      summary: Get all competitions
      responses:
        '200':
          description: Returns a list of all competitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/competition"
    post:
      tags: 
        - Competitions
      summary: Create a new competition
      description: Allows to create a new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/competition"
      responses:
        '201':
          description: Competition created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  competition:
                    $ref: "#/components/schemas/competition"
                required:
                  - competition

  /teams:
    get:
      tags:
        - Teams
      summary: Get all teams
      responses:
        '200':
          description: Returns a list of all teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/team"
    post:
      tags: 
        - Teams
      summary: Create a new team
      description: Allows to create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                  description: The name of the team
                tagline: 
                  type: string
                  description: The team tagline
      responses:
        '201':
          description: Team created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  team:
                    $ref: "#/components/schemas/team"
                required:
                  - team

  /player:
    get:
      tags:
        - Players
      summary: Get all players
      responses:
        '200':
          description: Returns a list of all players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/player"
    post:
      tags: 
        - Players
      summary: Create a new player
      description: Allows to create a new player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/player"
      responses:
        '201':
          description: Player created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  player:
                    $ref: "#/components/schemas/player"
                required:
                  - player

components:
  schemas:
    competition:
      type: object
      properties:
        name:
          type: string
          description: The name of the competition
        continent:
          type: string
          description: The country or the continent location
      required:
        - name
        - continent
        
    player:
      type: object
      properties:
        name:
          type: string
          description: The name of the player
        number:
          type: integer
          description: The number of the player
          format: int32
        footShooter: 
          type: string
          description: The foot that shoots of the player
      required:
        - name
        - number
      
    team:
      type: object
      properties:
        name:
          type: string
          description: The name of the team
        tagline:
          type: string
          description: The team tagline
        participatedCompetition:
          type: array
          items:
            $ref: "#/components/schemas/competition"
        playerList:
          type: array
          items:
            $ref: "#/components/schemas/player"
      required:
        - name
        - tagline
